name: simple_build_number
description: Simple BLoC that will help you with build number and react to their changes
authors:
  - CodeGrowers s.r.o.
version: 0.0.1
homepage: https://github.com/Code-Growers/simple_build_number

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 7.0.0
  localstorage: 4.0.0+1
  equatable: 2.0.3
  lognito:
    git:
      url: https://github.com/Code-Growers/lognito
      ref: null_safety

dev_dependencies:
  cg_analysis:
    git:
      url: https://github.com/Code-Growers/cg_analysis.git
      ref: master
